# Generated by Django 2.1.5 on 2019-01-15 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_interaction_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='messenger_id',
            field=models.IntegerField(default=0),
        ),
    ]
