# Generated by Django 2.1.5 on 2019-01-15 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_interaction_messenger_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='messenger_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
